import { DM_Sans, Inter, Poppins } from "next/font/google";
import { Metadata } from 'next';
import "./globals.css";
import { Providers } from "./Providers";


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({subsets:["latin"], weight:["100", "200", "300", "400", "500"]})
const dmSans = DM_Sans({subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Tualo Dashboard",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={`antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}